# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-vibration"
BBFILE_PATTERN_meta-vibration = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-vibration = "6"

LAYERDEPENDS_meta-vibration = "core"
LAYERSERIES_COMPAT_meta-vibration = "scarthgap"
